aws-samples/amazon-personalize-samples

personalize_temporal_holdout/metrics.py, personalize_temporal_holdout/personalize_temporal_holdout.ipynb
=> Example to temporally hold out data for external metric evaluations

personalize_sample_notebook.ipynb
Lots of python2 style print statements, I removed them and replaced them with python3 style.
=> Fixed compatability of prints for python3

personalize_temporal_holdout/personalize_temporal_holdout.ipynb
Add popularity baselines as examples for external evaluation methods.
=> add popularity baseline comparisons

README.md, personalize_temporal_holdout/README.md
*Description of changes:* Improve root REAMDE file. Move README for temporal holdout evaluation into the corresponding subfolder. Add a new section to introduce diagnose tools.
=> Move readme

getting_started/1.Building_Your_First_Campaign.ipynb, getting_started/2.View_Campaign_And_Interactions.ipynb, getting_started/Cleanup.ipynb
Previously the lab was challenging for many novices to complete due to the copy and pasting of values from one notebook to another. The getting started set has been refactored to leverage stored variables to make this process completely painless. This is proven to work for any valid IPython environment.
=> Now using stored variables

personalize_temporal_holdout/metrics.py, personalize_temporal_holdout/personalize_coldstart_demo.ipynb, personalize_temporal_holdout/personalize_temporal_holdout.ipynb
MRR should only consider the first element in the return list.
=> [Bugfix] Mean Reciprocal Rank

.gitignore, getting_started/ReInvent2019_Workshop.ipynb
1. Upgraded dataset to 1M interactions.
1. Upgraded boto3 for bulk exports
1. Moved bulk to optional bonus material.
=> upgraded to large dataset

getting_started/ReInvent2019_Workshop.ipynb
…bad structure in markdown
S3 turns out to default to Us-east-1, fix into the lab to correct this behavior.
=> S3 Region Fix

ml_ops/README.md
Small update to the README file
=> Updated README

advanced_examples/personalize_coldstart_demo.ipynb, advanced_examples/personalize_metadata_example.ipynb, advanced_examples/personalize_putEvents_demo.ipynb, advanced_examples/personalize_sims_smell_tests.ipynb, advanced_examples/personalize_temporal_holdout.ipynb
Edits to advanced_notebooks examples
=> Edits to advanced_examples notebooks

getting_started/notebooks/Best_Clientside_Security_Practices.ipynb
Adding notebook with best client side security practices.
=> Add Best_Clientside_Security_Practices notebook

next_steps/core_use_cases/user_personalization/user-personalization-with-exploration.ipynb
Add new recipe user personalization and use exploration config the help customer explore cold items.
=> Add user personalization recipe

next_steps/core_use_cases/user_personalization/user-personalization-with-exploration.ipynb
=> Fix bugs on the uploading file

next_steps/workshops/POC_in_a_box/PersonalizePOC.yaml, next_steps/workshops/POC_in_a_box/PersonalizePOCEE.yaml
*Issue #, if available:* We linked to the old repo, this fixes it.
*Description of changes:* Fixed all links to old repos in CF templates
=> updated CF links

PersonalizeCheatSheet2.0.md
*Issue #, if available:* A cheat sheet!
Just a list of crib like notes for Personalize to help out.
=> added the cheat sheet to the public repo

README.md, next_steps/core_use_cases/batch_recommendations/README.md, next_steps/workshops/README.md
Fixed some broken links to sub pages.
=> Fix broken links

next_steps/workshops/Immersion_Day/personalize_hrnn_metadata_contextual_example.ipynb
Cell failed to execute due to file path issue.
Fixed the file path to point to the right file.
=> fix failed execution due to file path

PersonalizeCheatSheet2.0.md
Content and formatting updates to the cheat sheet.
=> Cheat Sheet updates

next_steps/operations/ml_ops/personalize-step-functions/lambdas/create-solution/solution.py
=> fixing bug on create solution lambda function on the MLOps solution

PersonalizeCheatSheet2.0.md, README.md, next_steps/operations/README.md
Added links to Amazon Personalize Monitor project and Retail Demo Store demo/workshops.
=> Add links/content to monitor and retail demo store

getting_started/notebooks/1.Building_Your_First_Campaign.ipynb, next_steps/workshops/Reinvent_2019/ReInvent2019_Workshop.ipynb
=> iloc is 0-indexed, while movie-ids start with 1.

next_steps/README.md, next_steps/core_use_cases/README.md, next_steps/core_use_cases/batch_recommendations/README.md, next_steps/core_use_cases/personalized_ranking/README.md, next_steps/core_use_cases/related_items/README.md, next_steps/core_use_cases/user_personalization/README.md
Update use-case to recipe mappings to reflect latest recommendations and messaging.
=> Migrate recipes

getting_started/notebooks/1.Building_Your_First_Campaign.ipynb
=> add command to install unzip

next_steps/core_use_cases/related_items/aws-similar-items-with-metadata.ipynb
=> New example for aws-similar-items recipe

next_steps/operations/ml_ops/personalize-step-functions/template.yaml
=> Fix typo in the CloudFormation template

next_steps/operations/ml_ops/README.md
=> Fix typos in README.md

.gitignore, PersonalizeCheatSheet2.0.md, README.md, next_steps/README.md, next_steps/operations/README.md, next_steps/operations/filter_rotator/LICENSE, next_steps/operations/filter_rotator/README.md, next_steps/operations/filter_rotator/conftest.py, next_steps/operations/filter_rotator/src/filter_rotator_function/filter_rotator.py, next_steps/operations/filter_rotator/src/filter_rotator_function/requirements.txt, next_steps/operations/filter_rotator/src/filter_rotator_function/template_evaluation.py, next_steps/operations/filter_rotator/template.yaml, next_steps/operations/filter_rotator/tests/requirements.txt, next_steps/operations/filter_rotator/tests/unit/test_handler.py
- Add Personalize filter rotator serverless app to support automating the rotation of filters that use fixed values that need to change over time.
- Updated cheat sheet to include content on the new Similar-Items recipe and an FAQ for filter rotation.
=> Add filter rotator solution

next_steps/core_use_cases/user_segmentation/user_segmentation_example.ipynb
=> adding user segmentation notebook

PersonalizeCheatSheet2.0.md, README.md, next_steps/README.md, next_steps/operations/README.md
- Updated cheat sheet to include references to domain recommenders, user segmentation, personalization APIs, mParticle workshop.
- Added Personalization APIs project reference to list of operations related topics.
- Added link to User Segmentation notebook for core use cases.
=> Documentation updates

getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Video_On_Demand.ipynb, getting_started/notebooks_managed_domains/Clean_Up_Resources.ipynb
Fixes issue with error when deleting schemas
Updates variable names and readability
=> Fixes bugs and readability

getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Ecommerce.ipynb, getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Video_On_Demand.ipynb, getting_started/notebooks_managed_domains/Clean_Up_Resources.ipynb
Change the recommender to Customers who viewed X also viewed
The Frequently bought together recommender defaulted to popular items because of the small training dataset. Customers who viewed X also viewed is a better example.
Fix typos and update readability
=> Changing recommender and fix bugs

next_steps/workshops/magic_movie_machine/README.md, next_steps/workshops/magic_movie_machine/notebooks/Building the Magic Movie Machine Recommender.ipynb, next_steps/workshops/magic_movie_machine/notebooks/README.md
*Description of changes:* Fix syntax error and update readme files. 
=> Ashman improve readmes

getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Ecommerce.ipynb, getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Video_On_Demand.ipynb
Add error handling for the case when the s3 bucket already exists and just use it and raise any other errors.
=> Add s3 error handling for existing bucket

PersonalizeCheatSheet2.0.md, README.md, next_steps/README.md, next_steps/operations/README.md, next_steps/operations/filter_rotator/README.md
- Updated cheat sheet based on latest service changes
- De-emphasized the filter rotator solution and added content to clarify that the rotator is no longer needed (dynamic filters now support range operators)
=> Content updates based on latest features

next_steps/workshops/magic_movie_machine/notebooks/Building the Magic Movie Machine Recommender.ipynb
=> Add s3 error handling for existing bucket (same change made by Anna)

next_steps/core_use_cases/related_items/personalize_aws_similar_items_example.ipynb
- Resolve issue with notebook rendering within GitHub where the page formatting was broken due to embedded img tag.
- Fixed issue with links to Pantry dataset being broken.
- Added final step at the end of the notebook to delete campaigns to avoid ongoing charges.
=> Similar items notebook fixes

next_steps/core_use_cases/automatic_context/notebooks/1.Building_Personalize_Campaign.ipynb
- Changed name of PersonalizeRole as there may be conflicts with previous demo roles.
- Changed reference to TPS and pricing.
- Moved all store commands into one cell.
=> Changing role name, pricing reference and store calls

README.md
*Issue #, if available:* Not Applicable
*Description of changes:* Added an entry for a newly published aws-samples solution. This solution is a demo project to illustrate how to contextualize Amazon Personalize in case of live events. The newly published solution is at - https://github.com/aws-samples/amazon-personalize-live-event-contextualization . The core concept is illustrated in this blog - https://aws.amazon.com/blogs/media/part-3-contextualized-viewer-engagement-and-monetization-for-live-ott-events/
=> Addition of sample solution for livestream event contextualization

getting_started/notebooks_managed_domains/Building_Your_First_Recommender_Ecommerce.ipynb, getting_started/personalize_getting_started.yaml, next_steps/core_use_cases/filters/promotions/Promotions.ipynb, next_steps/core_use_cases/updating_datasets/sagemaker_notebook_exec_role.json, next_steps/core_use_cases/updating_datasets/update-datasets-user-personalization-example.ipynb, next_steps/core_use_cases/updating_datasets/update-item-dataset-schema-example.ipynb, next_steps/evaluation/measuring_impact_of_recommendations/Measure_Impact_of_Recommendations.ipynb
The Retail Demo Store public S3 staging buckets were recently converted to private buckets. Therefore, all references in samples needed to be updated to refer to the https URL for downloading CSVs. This pull requests includes those updates.
=> Update retail demo store bucket references

getting_started/README.md, next_steps/core_use_cases/automatic_context/README.md, next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/01_Introduction_and_Data_Preparation.ipynb, next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/README.md, next_steps/workshops/POC_in_a_box/README.md
The public Personalize staging buckets will be transitioned to private buckets and placed behind a CloudFront URL. This PR includes the changes necessary to change the direct links to public buckets.
=> Staging bucket changes

PersonalizeCheatSheet3.0.md
Personalize Cheat Sheet was out of date
Updating the Cheat Sheet to reflect recent changes in Amazon Personalize
=> Updating the Cheat Sheet Apr 2024

next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/01_Introduction_and_Data_Preparation.ipynb, next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/02_Train_Personalize_Model_01_Data.ipynb, next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/03_Train_Personalize_Model_02_Training.ipynb, next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/04_Personalized_Emails_with_Amazon_Personalize_and_Generative_AI.ipynb
Update Bedrock model to latest version and fix typos.
=> Update Bedrock model to latest version and fix typos.

next_steps/generative_ai/user_personalized_marketing_messaging_with_amazon_personalize_and_gen_ai/personalizeSimpleCFMarketingContentGen.yaml
add permissions to delete bucket objects on CF stack delete
=> add permissions to delete bucket objects on CF stack delete
